services:
    acm_api.event.authentication_success_listener:
        class: Acm\DatacollectorBundle\EventListener\AuthenticationSuccessListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    photo_uploader:
        class: Acm\DatacollectorBundle\Service\PictureUploader
        arguments: ['@photo_storage_filesystem']

    dob.listener:
        class: Acm\DatacollectorBundle\EventListener\DateofBirthListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    app.form_login_authenticator:
            class: Acm\DatacollectorBundle\Security\FormLoginAuthenticator
            arguments: ["@router", "@security.password_encoder"]

    app.datatable.human:
            class: Acm\DatacollectorBundle\Datatables\HumanDatatable
            parent: sg_datatables.datatable.abstract