services:
    acm_api.event.authentication_success_listener:
        class: Acm\DatacollectorBundle\EventListener\AuthenticationSuccessListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    acm_api.pic_uploader:
        class: Acm\DatacollectorBundle\Service\PictureUploader
        arguments: ['%pic.upload.dir%']

    dob.listener:
        class: Acm\DatacollectorBundle\EventListener\DateofBirthListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }