Acm\DatacollectorBundle\Entity\ApiUser:
    type:   entity
    table:  apiuser
    repositoryClass: Acm\DatacollectorBundle\Repository\ApiUserRepository

    gedmo:
        loggable: true
    id:
        id:
            type:   integer
            generator:
                strategy:   AUTO
    fields:
        username:
            type:   string
            unique: true
        apiKey:
            type: string
            unique: true
