Acm\DatacollectorBundle\Entity\Human:
    type:   entity
    table:  human
    repositoryClass: Acm\DatacollectorBundle\Repository\HumanRepository
    cache:
        usage : NONSTRICT_READ_WRITE
        region: region_human
    indexes:
        name_index:
           columns: [full_name]
        system_id_index:
           columns: [unique_id]
    gedmo:
        loggable: true
    id:
        id:
            type:   integer
            generator:
                strategy:   AUTO

    fields:
        fullName:
            type:   string
            length: 255
            column: full_name
        uniqueId:
            type: string
            length: 15
            column: unique_id
        dateOfBirth:
            type: date
            column: date_of_birth
        dobFlag:
            type: boolean
            column: dob_flag
        sex:
            type: string
            length: 10
        age:
            type: integer
        picture:
            type: string
            length: 255
            nullable: true
        verified:
            type: boolean
            nullable: true
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        houseHold:
            targetEntity: HouseHold
            inversedBy: human
            joinColumn:
                name: household_id
                referencedColumnName: id

        houseHoldRole:
            targetEntity: Acm\DatacollectorBundle\Entity\HouseHoldRole
            inversedBy: human
            joinColumn:
                name: house_hold_role_id
                referencedColumnName: id


    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue, setSystemIdValue ]
        preUpdate:  [ setUpdatedAtValue ]


