NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentaion

acm_datacollector:
    resource: "@AcmDatacollectorBundle/Resources/config/routing.yml"
    prefix:   /api

acm_registration:
    path: /dashboard/register
    defaults: {_controller: AcmDatacollectorBundle:User:register}

acm_dashboard:
    path: /dashboard/
    defaults: {_controller: AcmDatacollectorBundle:User:register}

#user_me:
#    path: /user/me/{apiKey}
#    defaults: {_controller: AcmDatacollectorBundle:User:findUser}
#    methods: [GET]

api_login_check:
    path: /api/login_check

