# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
         Acm\DatacollectorBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:                      [ROLE_ADMIN]
        ROLE_SUPER_ADMIN:                [ROLE_SUPER_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_MANAGER:                    [ROLE_MANAGER]
        ROLE_VERIFICATION_OFFICER:       [ROLE_VERIFICATION_OFFICER]
        ROLE_DATA_COLLECTOR:             [ROLE_DATA_COLLECTOR]

    providers:
        lb_db_provider:
            entity:
                class: Acm\DatacollectorBundle\Entity\User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                username_parameter: _username
                password_parameter: _password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name: bearer
        main:
            pattern:    ^/
            anonymous: ~
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path:   /logout

            remember_me:
                secret:      "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /
                domain:   ~


    access_control:
         - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/login,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }




