<?php

namespace Acm\DatacollectorBundle\Repository;

/**
 * HouseHoldRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseHoldRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
