<?php

namespace Acm\DatacollectorBundle\Repository;

/**
 * HouseHoldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseHoldRepository extends \Doctrine\ORM\EntityRepository
{
}
